version: '3.4'
services:
  db:
    container_name: labor-exchange_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["-c", "shared_buffers=2400MB", "-c", "work_mem=16MB", "-c", "fsync=off",
              "-c", "synchronous_commit=off", "-c", "full_page_writes=off",
              "-c", "checkpoint_timeout=15min", "-c", "max_wal_size=2GB"]

  service:
    container_name: labor-exchange_db
    image: ${LABOR_EXCHANGE_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DEBUG: ${APP_DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/opt/labor-exchange
    depends_on:
      - db