# Generated by Django 3.0.5 on 2020-05-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborexchangeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
