# Generated by Django 3.0.5 on 2020-05-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('logo', models.ImageField(height_field='205', null=True, upload_to='company_logos', verbose_name='Логотип', width_field='396')),
                ('employee_count', models.IntegerField(null=True, verbose_name='Количество сотрудников')),
                ('description', models.TextField(verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='userflow.LaborExchangeUser', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SpecialtyChoices.frontend', 'frontend'), ('SpecialtyChoices.backend', 'backend'), ('SpecialtyChoices.gamedev', 'gamedev'), ('SpecialtyChoices.devops', 'devops'), ('SpecialtyChoices.design', 'design'), ('SpecialtyChoices.products', 'products'), ('SpecialtyChoices.management', 'management'), ('SpecialtyChoices.testing', 'testing')], max_length=50, verbose_name='Код')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('picture', models.ImageField(height_field='148', null=True, upload_to='specialty', verbose_name='Изображение', width_field='148')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Зарплата, нижняя граница')),
                ('salary_max', models.IntegerField(verbose_name='Зарплата, верхняя граница')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='workflow.Company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='workflow.Specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='userflow.LaborExchangeUser', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workflow.Vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['vacancy', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('status', models.CharField(choices=[('WorkStatusChoices.not_in_search', 'Не ищу работу'), ('WorkStatusChoices.consideration', 'Рассматриваю предложения'), ('WorkStatusChoices.in_search', 'Ищу работу')], max_length=50, verbose_name='Поисковый статус')),
                ('grade', models.CharField(choices=[('GradeChoices.intern', 'intern'), ('GradeChoices.junior', 'junior'), ('GradeChoices.middle', 'middle'), ('GradeChoices.senior', 'senior'), ('GradeChoices.lead', 'lead')], max_length=50, verbose_name='Квалификация')),
                ('education', models.CharField(choices=[('EducationChoices.missing', 'Отсутствует'), ('EducationChoices.secondary', 'Среднее'), ('EducationChoices.vocational', 'Средне-специальное'), ('EducationChoices.incomplete_higher', 'Неполное высшее'), ('EducationChoices.higher', 'Высшее')], max_length=250, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='workflow.Specialty', verbose_name='Специализация')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='userflow.LaborExchangeUser', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['surname', 'name'],
            },
        ),
    ]
