# Generated by Django 3.0.5 on 2020-04-28 18:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('logo', models.ImageField(height_field='205', null=True, upload_to='company_logos', verbose_name='Логотип', width_field='396')),
                ('description', models.TextField(verbose_name='Описание')),
                ('employee_count', models.IntegerField(null=True, verbose_name='Количество сотрудников')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SpecialtyChoices.frontend', 'frontend'), ('SpecialtyChoices.backend', 'backend'), ('SpecialtyChoices.gamedev', 'gamedev'), ('SpecialtyChoices.devops', 'devops'), ('SpecialtyChoices.design', 'design'), ('SpecialtyChoices.products', 'products'), ('SpecialtyChoices.management', 'management'), ('SpecialtyChoices.testing', 'testing')], max_length=50, verbose_name='Код')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('picture', models.ImageField(height_field='148', null=True, upload_to='specialty', verbose_name='Изображение', width_field='148')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='Кодовое имя')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Зарплата, нижняя граница')),
                ('salary_max', models.IntegerField(verbose_name='Зарплата, верхняя граница')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Specialty', verbose_name='Специальность')),
            ],
        ),
    ]
