# Generated by Django 3.0.5 on 2020-05-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SpecialtyChoices.frontend', 'Фронтенд'), ('SpecialtyChoices.backend', 'Бэкенд'), ('SpecialtyChoices.gamedev', 'Геймдев'), ('SpecialtyChoices.devops', 'Девопс'), ('SpecialtyChoices.design', 'Дизайн'), ('SpecialtyChoices.products', 'Продукты'), ('SpecialtyChoices.management', 'Менеджмент'), ('SpecialtyChoices.testing', 'Тестирование')], max_length=50, verbose_name='Код')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('picture', models.ImageField(null=True, upload_to='specialty_logos', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата, нижняя граница')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата, верхняя граница')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.Company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.Specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['title'],
            },
        ),
    ]
